### PR TITLE
Update to leaflet.fullscreen v1.6.x

### PR DESCRIPTION
**Pull request by dansoliveira**
Fix issue #9

### CODE REVIEW

**Comment by dylan-13** [comment]
@krvital please we need this fix 😢

**Review by dylan-13 — APPROVED** [review]

**Comment by krvital** [comment]
@dylan-13 been preparing major update. Hope to release this week

**Comment by krvital** [comment]
Have been busy this week. The only I can promise is to try to look at it next week.

**Comment by krvital** [comment]
It seems like I fixed the issue. I’ve introduced new version 2 which works with react-leaflet v3. There is also still v1 where I update leaflet.fullscreen version

**Pull request closed without merging**
